// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsfftcTCzLSsEprrlx6gzt34pQEPmELeI',
    appId: '1:29447079750:web:1793c47e5403f60db90747',
    messagingSenderId: '29447079750',
    projectId: 'msmart-38e91',
    authDomain: 'msmart-38e91.firebaseapp.com',
    storageBucket: 'msmart-38e91.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS8qfZ3yjX2iw_m9aXc2v30sFUDqzfaI0',
    appId: '1:29447079750:android:9553f304a0290645b90747',
    messagingSenderId: '29447079750',
    projectId: 'msmart-38e91',
    storageBucket: 'msmart-38e91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8WToUVVx3UgEkzNz-B77Hgcm95jg9uxI',
    appId: '1:29447079750:ios:f800e31e1e79f85fb90747',
    messagingSenderId: '29447079750',
    projectId: 'msmart-38e91',
    storageBucket: 'msmart-38e91.firebasestorage.app',
    iosBundleId: 'com.example.msmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8WToUVVx3UgEkzNz-B77Hgcm95jg9uxI',
    appId: '1:29447079750:ios:f800e31e1e79f85fb90747',
    messagingSenderId: '29447079750',
    projectId: 'msmart-38e91',
    storageBucket: 'msmart-38e91.firebasestorage.app',
    iosBundleId: 'com.example.msmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsfftcTCzLSsEprrlx6gzt34pQEPmELeI',
    appId: '1:29447079750:web:ce2a59adcc4187d6b90747',
    messagingSenderId: '29447079750',
    projectId: 'msmart-38e91',
    authDomain: 'msmart-38e91.firebaseapp.com',
    storageBucket: 'msmart-38e91.firebasestorage.app',
  );
}
